// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqyoiepxonuuitdagget.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeW9pZXB4b251dWl0ZGFnZ2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzgzMjgsImV4cCI6MjA2OTg1NDMyOH0.2o8UCloWX-BrgysYb8A45MNO2wFUCBQS92c9mg0JXVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});